name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v6.0.0
      - uses: actions/setup-node@v3
      - name: Setup Go environment
        uses: actions/setup-go@v5.6.0
        with:
          node-version: '14'
      
      - run: bats -v
              
          
